import { randomUUID } from 'crypto';
import { db, schema } from './index';

const { analysisFrameworks } = schema;

interface FrameworkDef {
  categoryKey: string;
  categoryName: string;
  description: string;
  analysisTypes: { index: number; name: string }[];
}

const frameworks: FrameworkDef[] = [
  {
    categoryKey: 'reliable-ai',
    categoryName: 'Reliable AI',
    description: 'Assess AI system reliability across operational conditions',
    analysisTypes: [
      { index: 1, name: 'System Uptime Analysis' },
      { index: 2, name: 'Fault Tolerance Assessment' },
      { index: 3, name: 'Error Recovery Analysis' },
      { index: 4, name: 'Performance Consistency Check' },
      { index: 5, name: 'Load Handling Evaluation' },
      { index: 6, name: 'Data Pipeline Reliability' },
      { index: 7, name: 'Model Stability Testing' },
      { index: 8, name: 'Redundancy Assessment' },
      { index: 9, name: 'Degradation Pattern Analysis' },
      { index: 10, name: 'Failover Mechanism Audit' },
      { index: 11, name: 'Input Validation Reliability' },
      { index: 12, name: 'Output Consistency Verification' },
      { index: 13, name: 'Cross-Platform Reliability' },
      { index: 14, name: 'Temporal Stability Analysis' },
      { index: 15, name: 'Edge Case Handling' },
      { index: 16, name: 'Concurrency Reliability' },
      { index: 17, name: 'Dependency Reliability Audit' },
      { index: 18, name: 'SLA Compliance Check' },
    ],
  },
  {
    categoryKey: 'trustworthy-ai',
    categoryName: 'Trustworthy AI',
    description: 'Evaluate trustworthiness of AI decisions and outputs',
    analysisTypes: [
      { index: 1, name: 'Decision Transparency Analysis' },
      { index: 2, name: 'Prediction Confidence Scoring' },
      { index: 3, name: 'Bias Detection Assessment' },
      { index: 4, name: 'Data Provenance Verification' },
      { index: 5, name: 'Stakeholder Trust Survey' },
      { index: 6, name: 'Reproducibility Testing' },
      { index: 7, name: 'Audit Trail Completeness' },
      { index: 8, name: 'Third-Party Validation' },
      { index: 9, name: 'Consistency Across Demographics' },
      { index: 10, name: 'Uncertainty Quantification' },
      { index: 11, name: 'User Feedback Integration' },
      { index: 12, name: 'Regulatory Alignment Check' },
      { index: 13, name: 'Ethical Guidelines Compliance' },
      { index: 14, name: 'Factual Accuracy Verification' },
      { index: 15, name: 'Source Attribution Analysis' },
      { index: 16, name: 'Conflict of Interest Screening' },
      { index: 17, name: 'Version Control Integrity' },
      { index: 18, name: 'Trust Score Benchmarking' },
    ],
  },
  {
    categoryKey: 'safe-ai',
    categoryName: 'Safe AI',
    description: 'Assess safety measures and risk mitigation in AI systems',
    analysisTypes: [
      { index: 1, name: 'Harm Prevention Assessment' },
      { index: 2, name: 'Safety Boundary Testing' },
      { index: 3, name: 'Adversarial Attack Resilience' },
      { index: 4, name: 'Content Safety Filtering' },
      { index: 5, name: 'Physical Safety Compliance' },
      { index: 6, name: 'Psychological Impact Analysis' },
      { index: 7, name: 'Autonomous Decision Safeguards' },
      { index: 8, name: 'Emergency Shutdown Protocols' },
      { index: 9, name: 'Risk Escalation Procedures' },
      { index: 10, name: 'Safety Testing Coverage' },
      { index: 11, name: 'Human Override Mechanisms' },
      { index: 12, name: 'Containment Measures Audit' },
      { index: 13, name: 'Failure Mode Analysis' },
      { index: 14, name: 'Safety Certification Status' },
      { index: 15, name: 'Incident Response Readiness' },
      { index: 16, name: 'Safety Monitoring Effectiveness' },
      { index: 17, name: 'User Safety Documentation' },
      { index: 18, name: 'Safety Update Frequency' },
    ],
  },
  {
    categoryKey: 'accountable-ai',
    categoryName: 'Accountable AI',
    description: 'Evaluate accountability structures for AI systems',
    analysisTypes: [
      { index: 1, name: 'Responsibility Assignment Matrix' },
      { index: 2, name: 'Decision Logging Completeness' },
      { index: 3, name: 'Stakeholder Communication' },
      { index: 4, name: 'Impact Assessment Documentation' },
      { index: 5, name: 'Grievance Mechanism Availability' },
      { index: 6, name: 'Remediation Process Evaluation' },
      { index: 7, name: 'Compliance Reporting Accuracy' },
      { index: 8, name: 'Liability Framework Clarity' },
      { index: 9, name: 'Oversight Committee Effectiveness' },
      { index: 10, name: 'Performance Accountability Metrics' },
      { index: 11, name: 'Incident Accountability Tracking' },
      { index: 12, name: 'Budget Accountability Analysis' },
      { index: 13, name: 'Timeline Adherence Audit' },
      { index: 14, name: 'Quality Assurance Accountability' },
      { index: 15, name: 'External Audit Compliance' },
      { index: 16, name: 'Transparency Report Quality' },
      { index: 17, name: 'Continuous Improvement Tracking' },
      { index: 18, name: 'Accountability Score Benchmarking' },
    ],
  },
  {
    categoryKey: 'auditable-ai',
    categoryName: 'Auditable AI',
    description: 'Assess auditability of AI processes and decisions',
    analysisTypes: [
      { index: 1, name: 'Audit Trail Completeness' },
      { index: 2, name: 'Data Lineage Traceability' },
      { index: 3, name: 'Model Version Tracking' },
      { index: 4, name: 'Configuration Change Logging' },
      { index: 5, name: 'Access Control Audit' },
      { index: 6, name: 'Decision Reconstruction Capability' },
      { index: 7, name: 'Regulatory Audit Readiness' },
      { index: 8, name: 'Documentation Sufficiency' },
      { index: 9, name: 'Automated Audit Tool Coverage' },
      { index: 10, name: 'Audit Frequency Compliance' },
      { index: 11, name: 'Finding Remediation Tracking' },
      { index: 12, name: 'Evidence Preservation Quality' },
      { index: 13, name: 'Audit Report Standardization' },
      { index: 14, name: 'Cross-System Audit Integration' },
      { index: 15, name: 'Auditor Access Provisioning' },
      { index: 16, name: 'Audit Scope Completeness' },
      { index: 17, name: 'Audit Exception Management' },
      { index: 18, name: 'Audit Maturity Assessment' },
    ],
  },
  {
    categoryKey: 'model-lifecycle',
    categoryName: 'Model Lifecycle',
    description: 'Evaluate model development, deployment, and retirement processes',
    analysisTypes: [
      { index: 1, name: 'Requirements Specification Quality' },
      { index: 2, name: 'Data Collection Standards' },
      { index: 3, name: 'Feature Engineering Assessment' },
      { index: 4, name: 'Training Process Documentation' },
      { index: 5, name: 'Validation Strategy Evaluation' },
      { index: 6, name: 'Testing Coverage Analysis' },
      { index: 7, name: 'Deployment Readiness Check' },
      { index: 8, name: 'Production Monitoring Setup' },
      { index: 9, name: 'Performance Tracking Metrics' },
      { index: 10, name: 'Retraining Trigger Criteria' },
      { index: 11, name: 'Model Registry Management' },
      { index: 12, name: 'A/B Testing Framework' },
      { index: 13, name: 'Rollback Procedure Readiness' },
      { index: 14, name: 'Deprecation Planning' },
      { index: 15, name: 'Knowledge Transfer Process' },
      { index: 16, name: 'Resource Utilization Tracking' },
      { index: 17, name: 'Stakeholder Sign-Off Process' },
      { index: 18, name: 'Lifecycle Maturity Score' },
    ],
  },
  {
    categoryKey: 'monitoring-drift',
    categoryName: 'Monitoring & Drift',
    description: 'Monitor AI model performance and detect distribution drift',
    analysisTypes: [
      { index: 1, name: 'Data Drift Detection' },
      { index: 2, name: 'Concept Drift Analysis' },
      { index: 3, name: 'Prediction Drift Monitoring' },
      { index: 4, name: 'Feature Importance Shift' },
      { index: 5, name: 'Performance Degradation Alerts' },
      { index: 6, name: 'Statistical Distribution Comparison' },
      { index: 7, name: 'Covariate Shift Analysis' },
      { index: 8, name: 'Label Drift Detection' },
      { index: 9, name: 'Seasonal Pattern Analysis' },
      { index: 10, name: 'Outlier Volume Tracking' },
      { index: 11, name: 'Model Freshness Score' },
      { index: 12, name: 'Retraining Necessity Assessment' },
      { index: 13, name: 'Drift Impact Quantification' },
      { index: 14, name: 'Monitoring Coverage Audit' },
      { index: 15, name: 'Alert Configuration Review' },
      { index: 16, name: 'Dashboard Effectiveness' },
      { index: 17, name: 'Automated Response Evaluation' },
      { index: 18, name: 'Drift Resilience Score' },
    ],
  },
  {
    categoryKey: 'sustainable-green-ai',
    categoryName: 'Sustainable / Green AI',
    description: 'Evaluate environmental sustainability of AI operations',
    analysisTypes: [
      { index: 1, name: 'Carbon Footprint Measurement' },
      { index: 2, name: 'Energy Consumption Tracking' },
      { index: 3, name: 'Compute Efficiency Analysis' },
      { index: 4, name: 'Hardware Utilization Rate' },
      { index: 5, name: 'Model Compression Assessment' },
      { index: 6, name: 'Green Energy Usage Percentage' },
      { index: 7, name: 'Water Usage for Cooling' },
      { index: 8, name: 'E-Waste Management Plan' },
      { index: 9, name: 'Training Efficiency Optimization' },
      { index: 10, name: 'Inference Cost Analysis' },
      { index: 11, name: 'Data Storage Footprint' },
      { index: 12, name: 'Network Transfer Efficiency' },
      { index: 13, name: 'Sustainability Reporting Compliance' },
      { index: 14, name: 'Lifecycle Environmental Impact' },
      { index: 15, name: 'Green Vendor Assessment' },
      { index: 16, name: 'Offset Program Participation' },
      { index: 17, name: 'Sustainability Target Progress' },
      { index: 18, name: 'Green AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'responsible-genai',
    categoryName: 'Responsible GenAI',
    description: 'Evaluate responsible use of generative AI systems',
    analysisTypes: [
      { index: 1, name: 'Content Generation Guardrails' },
      { index: 2, name: 'Misinformation Prevention' },
      { index: 3, name: 'Copyright Compliance Check' },
      { index: 4, name: 'Deepfake Detection Capability' },
      { index: 5, name: 'Attribution and Citation' },
      { index: 6, name: 'Harmful Content Filtering' },
      { index: 7, name: 'Consent Management for Training Data' },
      { index: 8, name: 'Output Disclosure Requirements' },
      { index: 9, name: 'Human Review Workflow' },
      { index: 10, name: 'Prompt Injection Prevention' },
      { index: 11, name: 'Data Leakage Prevention' },
      { index: 12, name: 'Bias in Generation Assessment' },
      { index: 13, name: 'Quality Assurance Pipeline' },
      { index: 14, name: 'Use Case Restriction Enforcement' },
      { index: 15, name: 'Feedback Loop Management' },
      { index: 16, name: 'Regulatory Compliance Mapping' },
      { index: 17, name: 'Ethical Review Process' },
      { index: 18, name: 'Responsible GenAI Maturity Score' },
    ],
  },
  {
    categoryKey: 'debug-ai',
    categoryName: 'Debug AI',
    description: 'Assess debugging capabilities and error analysis for AI systems',
    analysisTypes: [
      { index: 1, name: 'Error Classification Framework' },
      { index: 2, name: 'Root Cause Analysis Capability' },
      { index: 3, name: 'Logging Infrastructure Quality' },
      { index: 4, name: 'Debugging Tool Coverage' },
      { index: 5, name: 'Model Introspection Capability' },
      { index: 6, name: 'Data Quality Diagnostics' },
      { index: 7, name: 'Pipeline Error Tracking' },
      { index: 8, name: 'Regression Detection Automation' },
      { index: 9, name: 'Performance Profiling Tools' },
      { index: 10, name: 'Memory and Resource Debugging' },
      { index: 11, name: 'Distributed System Tracing' },
      { index: 12, name: 'Feature Attribution Debugging' },
      { index: 13, name: 'Batch vs Real-Time Discrepancy' },
      { index: 14, name: 'Environment Reproducibility' },
      { index: 15, name: 'Error Impact Assessment' },
      { index: 16, name: 'Debug Documentation Quality' },
      { index: 17, name: 'Automated Bug Detection' },
      { index: 18, name: 'Debug Response Time Analysis' },
      { index: 19, name: 'Issue Escalation Workflow' },
      { index: 20, name: 'Debug Maturity Score' },
    ],
  },
  {
    categoryKey: 'portability-ai',
    categoryName: 'Portability AI',
    description: 'Evaluate AI system portability across platforms and environments',
    analysisTypes: [
      { index: 1, name: 'Framework Independence Assessment' },
      { index: 2, name: 'Platform Compatibility Testing' },
      { index: 3, name: 'Data Format Standardization' },
      { index: 4, name: 'Model Export Format Support' },
      { index: 5, name: 'API Abstraction Layer Quality' },
      { index: 6, name: 'Containerization Readiness' },
      { index: 7, name: 'Cloud Provider Portability' },
      { index: 8, name: 'Hardware Abstraction Assessment' },
      { index: 9, name: 'Configuration Externalization' },
      { index: 10, name: 'Dependency Management Quality' },
      { index: 11, name: 'Migration Effort Estimation' },
      { index: 12, name: 'Cross-Language Support' },
      { index: 13, name: 'Backward Compatibility Testing' },
      { index: 14, name: 'Deployment Flexibility Score' },
      { index: 15, name: 'Edge Deployment Readiness' },
      { index: 16, name: 'Vendor Lock-In Assessment' },
      { index: 17, name: 'Documentation for Migration' },
      { index: 18, name: 'Portability Maturity Score' },
    ],
  },
  {
    categoryKey: 'interpretable-ai',
    categoryName: 'Interpretable AI',
    description: 'Assess interpretability of AI model decisions and behavior',
    analysisTypes: [
      { index: 1, name: 'Model Complexity Assessment' },
      { index: 2, name: 'Feature Contribution Analysis' },
      { index: 3, name: 'Decision Rule Extraction' },
      { index: 4, name: 'Local Interpretability Methods' },
      { index: 5, name: 'Global Interpretability Methods' },
      { index: 6, name: 'Visualization Quality Assessment' },
      { index: 7, name: 'Counterfactual Explanation' },
      { index: 8, name: 'Concept-Based Explanation' },
      { index: 9, name: 'Model Simplification Analysis' },
      { index: 10, name: 'Stakeholder Comprehension Testing' },
      { index: 11, name: 'Domain Expert Validation' },
      { index: 12, name: 'Explanation Consistency Check' },
      { index: 13, name: 'Interpretation Tool Coverage' },
      { index: 14, name: 'Natural Language Explanation' },
      { index: 15, name: 'Attention Mechanism Analysis' },
      { index: 16, name: 'Layer-wise Analysis Capability' },
      { index: 17, name: 'Explanation Fidelity Score' },
      { index: 18, name: 'Interpretability Maturity Score' },
    ],
  },
  {
    categoryKey: 'trust-ai',
    categoryName: 'Trust AI',
    description: 'Measure and build trust in AI systems across stakeholders',
    analysisTypes: [
      { index: 1, name: 'User Trust Level Assessment' },
      { index: 2, name: 'System Reliability Perception' },
      { index: 3, name: 'Transparency Communication' },
      { index: 4, name: 'Prediction Accuracy Trust' },
      { index: 5, name: 'Data Handling Trust' },
      { index: 6, name: 'Privacy Assurance Evaluation' },
      { index: 7, name: 'Consent Transparency' },
      { index: 8, name: 'Accountability Perception' },
      { index: 9, name: 'Fairness Perception' },
      { index: 10, name: 'Error Communication Quality' },
      { index: 11, name: 'Feedback Responsiveness' },
      { index: 12, name: 'Trust Recovery After Incidents' },
      { index: 13, name: 'Stakeholder Engagement Quality' },
      { index: 14, name: 'Brand Trust Impact' },
      { index: 15, name: 'Regulatory Trust Compliance' },
      { index: 16, name: 'Industry Trust Benchmarking' },
      { index: 17, name: 'Trust Building Initiatives' },
      { index: 18, name: 'Trust Maturity Score' },
    ],
  },
  {
    categoryKey: 'responsible-ai',
    categoryName: 'Responsible AI',
    description: 'Evaluate responsible AI practices across the development lifecycle',
    analysisTypes: [
      { index: 1, name: 'Ethical Impact Assessment' },
      { index: 2, name: 'Stakeholder Impact Analysis' },
      { index: 3, name: 'Inclusive Design Evaluation' },
      { index: 4, name: 'Community Impact Assessment' },
      { index: 5, name: 'Value Alignment Check' },
      { index: 6, name: 'Power Dynamics Analysis' },
      { index: 7, name: 'Consent and Autonomy Respect' },
      { index: 8, name: 'Cultural Sensitivity Review' },
      { index: 9, name: 'Accessibility Compliance' },
      { index: 10, name: 'Digital Divide Consideration' },
      { index: 11, name: 'Labor Impact Assessment' },
      { index: 12, name: 'Environmental Responsibility' },
      { index: 13, name: 'Data Responsibility Audit' },
      { index: 14, name: 'Algorithm Responsibility Check' },
      { index: 15, name: 'Deployment Responsibility' },
      { index: 16, name: 'Post-Deployment Monitoring' },
      { index: 17, name: 'Responsible Innovation Practices' },
      { index: 18, name: 'Responsible Decommissioning' },
      { index: 19, name: 'Responsibility Governance' },
      { index: 20, name: 'Responsible AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'explainable-ai',
    categoryName: 'Explainable AI',
    description: 'Assess ability to explain AI decision-making processes',
    analysisTypes: [
      { index: 1, name: 'SHAP Value Analysis' },
      { index: 2, name: 'LIME Explanation Quality' },
      { index: 3, name: 'Feature Importance Ranking' },
      { index: 4, name: 'Partial Dependence Plots' },
      { index: 5, name: 'Counterfactual Generation' },
      { index: 6, name: 'Attention Visualization' },
      { index: 7, name: 'Decision Tree Surrogate' },
      { index: 8, name: 'Rule Extraction Quality' },
      { index: 9, name: 'Explanation Completeness' },
      { index: 10, name: 'Explanation Correctness' },
      { index: 11, name: 'User Study Evaluation' },
      { index: 12, name: 'Multi-Level Explanation' },
      { index: 13, name: 'Temporal Explanation' },
      { index: 14, name: 'Contrastive Explanation' },
      { index: 15, name: 'Interactive Explanation UI' },
      { index: 16, name: 'Domain-Specific Explanation' },
      { index: 17, name: 'Explanation Robustness' },
      { index: 18, name: 'Explanation Efficiency' },
      { index: 19, name: 'Regulatory Explanation Compliance' },
      { index: 20, name: 'Explainability Maturity Score' },
    ],
  },
  {
    categoryKey: 'fairness-ai',
    categoryName: 'Fairness AI',
    description: 'Evaluate fairness and bias mitigation in AI systems',
    analysisTypes: [
      { index: 1, name: 'Demographic Parity Analysis' },
      { index: 2, name: 'Equal Opportunity Assessment' },
      { index: 3, name: 'Equalized Odds Check' },
      { index: 4, name: 'Disparate Impact Ratio' },
      { index: 5, name: 'Calibration Across Groups' },
      { index: 6, name: 'Representation Audit' },
      { index: 7, name: 'Historical Bias Detection' },
      { index: 8, name: 'Measurement Bias Assessment' },
      { index: 9, name: 'Aggregation Bias Check' },
      { index: 10, name: 'Evaluation Bias Analysis' },
      { index: 11, name: 'Pre-Processing Fairness' },
      { index: 12, name: 'In-Processing Fairness' },
      { index: 13, name: 'Post-Processing Fairness' },
      { index: 14, name: 'Intersectional Fairness' },
      { index: 15, name: 'Individual Fairness Check' },
      { index: 16, name: 'Fairness Constraint Trade-offs' },
      { index: 17, name: 'Bias Mitigation Effectiveness' },
      { index: 18, name: 'Fairness Maturity Score' },
    ],
  },
  {
    categoryKey: 'mechanistic-causal-ai',
    categoryName: 'Mechanistic & Causal AI',
    description: 'Assess causal reasoning and mechanistic understanding in AI',
    analysisTypes: [
      { index: 1, name: 'Causal Graph Construction' },
      { index: 2, name: 'Intervention Analysis' },
      { index: 3, name: 'Counterfactual Reasoning' },
      { index: 4, name: 'Mediation Analysis' },
      { index: 5, name: 'Confounding Variable Detection' },
      { index: 6, name: 'Causal Discovery Methods' },
      { index: 7, name: 'Structural Equation Modeling' },
      { index: 8, name: 'Treatment Effect Estimation' },
      { index: 9, name: 'Instrumental Variable Analysis' },
      { index: 10, name: 'Do-Calculus Application' },
      { index: 11, name: 'Mechanism Identification' },
      { index: 12, name: 'Causal Feature Selection' },
      { index: 13, name: 'Temporal Causal Analysis' },
      { index: 14, name: 'Causal Robustness Testing' },
      { index: 15, name: 'Domain Knowledge Integration' },
      { index: 16, name: 'Causal Explanation Quality' },
      { index: 17, name: 'Causal Inference Validation' },
      { index: 18, name: 'Causal AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'human-centered-ai',
    categoryName: 'Human-Centered AI',
    description: 'Evaluate human-centric design and interaction patterns',
    analysisTypes: [
      { index: 1, name: 'User Experience Assessment' },
      { index: 2, name: 'Cognitive Load Analysis' },
      { index: 3, name: 'Accessibility Compliance' },
      { index: 4, name: 'User Agency Preservation' },
      { index: 5, name: 'Task Completion Efficiency' },
      { index: 6, name: 'Error Recovery Design' },
      { index: 7, name: 'Feedback Mechanism Quality' },
      { index: 8, name: 'Personalization Assessment' },
      { index: 9, name: 'Onboarding Effectiveness' },
      { index: 10, name: 'Mental Model Alignment' },
      { index: 11, name: 'Emotional Impact Assessment' },
      { index: 12, name: 'Cultural Adaptation' },
      { index: 13, name: 'Multi-Modal Interaction' },
      { index: 14, name: 'User Control and Customization' },
      { index: 15, name: 'Help and Documentation Quality' },
      { index: 16, name: 'User Research Integration' },
      { index: 17, name: 'Co-Design Practices' },
      { index: 18, name: 'Human-Centered Maturity Score' },
    ],
  },
  {
    categoryKey: 'human-in-the-loop-ai',
    categoryName: 'Human-in-the-Loop AI',
    description: 'Assess human oversight and intervention capabilities',
    analysisTypes: [
      { index: 1, name: 'Human Override Capability' },
      { index: 2, name: 'Review Workflow Effectiveness' },
      { index: 3, name: 'Escalation Path Clarity' },
      { index: 4, name: 'Decision Support Quality' },
      { index: 5, name: 'Automation Level Appropriateness' },
      { index: 6, name: 'Human Feedback Integration' },
      { index: 7, name: 'Active Learning Pipeline' },
      { index: 8, name: 'Annotation Quality Control' },
      { index: 9, name: 'Expert Panel Access' },
      { index: 10, name: 'Real-Time Intervention UI' },
      { index: 11, name: 'Confidence Threshold Calibration' },
      { index: 12, name: 'Workload Distribution' },
      { index: 13, name: 'Human Fatigue Management' },
      { index: 14, name: 'Skill Gap Assessment' },
      { index: 15, name: 'Training and Certification' },
      { index: 16, name: 'Performance Monitoring of Reviewers' },
      { index: 17, name: 'Cost-Benefit of Human Review' },
      { index: 18, name: 'HITL Maturity Score' },
    ],
  },
  {
    categoryKey: 'transparent-data-ai',
    categoryName: 'Transparent Data AI',
    description: 'Evaluate data transparency and documentation practices',
    analysisTypes: [
      { index: 1, name: 'Data Source Documentation' },
      { index: 2, name: 'Data Collection Methodology' },
      { index: 3, name: 'Data Quality Metrics' },
      { index: 4, name: 'Data Labeling Transparency' },
      { index: 5, name: 'Data Preprocessing Documentation' },
      { index: 6, name: 'Feature Engineering Transparency' },
      { index: 7, name: 'Data Versioning Practices' },
      { index: 8, name: 'Data Access Controls' },
      { index: 9, name: 'Data Retention Policies' },
      { index: 10, name: 'Data Sharing Agreements' },
      { index: 11, name: 'Data Bias Documentation' },
      { index: 12, name: 'Missing Data Handling' },
      { index: 13, name: 'Data Augmentation Disclosure' },
      { index: 14, name: 'Synthetic Data Documentation' },
      { index: 15, name: 'Data Governance Framework' },
      { index: 16, name: 'Data Impact Assessment' },
      { index: 17, name: 'Open Data Initiatives' },
      { index: 18, name: 'Data Transparency Maturity Score' },
    ],
  },
  {
    categoryKey: 'social-ai',
    categoryName: 'Social AI',
    description: 'Assess social impact and societal implications of AI',
    analysisTypes: [
      { index: 1, name: 'Social Benefit Assessment' },
      { index: 2, name: 'Community Impact Analysis' },
      { index: 3, name: 'Digital Divide Impact' },
      { index: 4, name: 'Employment Impact Assessment' },
      { index: 5, name: 'Education Impact Analysis' },
      { index: 6, name: 'Healthcare Equity Impact' },
      { index: 7, name: 'Public Safety Assessment' },
      { index: 8, name: 'Democratic Process Impact' },
      { index: 9, name: 'Misinformation Propagation Risk' },
      { index: 10, name: 'Social Cohesion Impact' },
      { index: 11, name: 'Cultural Preservation' },
      { index: 12, name: 'Accessibility for Vulnerable Groups' },
      { index: 13, name: 'Human Rights Compliance' },
      { index: 14, name: 'Public Engagement Quality' },
      { index: 15, name: 'Social Responsibility Reporting' },
      { index: 16, name: 'Stakeholder Inclusivity' },
      { index: 17, name: 'Long-Term Social Impact' },
      { index: 18, name: 'Social AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'compliance-ai',
    categoryName: 'Compliance AI',
    description: 'Evaluate regulatory compliance of AI systems',
    analysisTypes: [
      { index: 1, name: 'GDPR Compliance Assessment' },
      { index: 2, name: 'CCPA Compliance Check' },
      { index: 3, name: 'EU AI Act Alignment' },
      { index: 4, name: 'HIPAA Compliance Audit' },
      { index: 5, name: 'SOC 2 Type II Readiness' },
      { index: 6, name: 'ISO 27001 Alignment' },
      { index: 7, name: 'NIST AI RMF Compliance' },
      { index: 8, name: 'Industry-Specific Regulations' },
      { index: 9, name: 'Cross-Border Data Compliance' },
      { index: 10, name: 'Consent Management Compliance' },
      { index: 11, name: 'Data Subject Rights Fulfillment' },
      { index: 12, name: 'Automated Decision Making Disclosure' },
      { index: 13, name: 'Record Keeping Requirements' },
      { index: 14, name: 'Breach Notification Readiness' },
      { index: 15, name: 'DPO Assignment and Training' },
      { index: 16, name: 'Compliance Training Coverage' },
      { index: 17, name: 'Regulatory Change Monitoring' },
      { index: 18, name: 'Compliance Audit Frequency' },
      { index: 19, name: 'Penalty Risk Assessment' },
      { index: 20, name: 'Compliance Maturity Score' },
    ],
  },
  {
    categoryKey: 'privacy-preserving-ai',
    categoryName: 'Privacy-Preserving AI',
    description: 'Evaluate privacy protection measures in AI systems',
    analysisTypes: [
      { index: 1, name: 'Differential Privacy Implementation' },
      { index: 2, name: 'Federated Learning Assessment' },
      { index: 3, name: 'Homomorphic Encryption Usage' },
      { index: 4, name: 'Secure Multi-Party Computation' },
      { index: 5, name: 'Data Anonymization Quality' },
      { index: 6, name: 'Pseudonymization Effectiveness' },
      { index: 7, name: 'Re-Identification Risk Assessment' },
      { index: 8, name: 'Privacy Impact Assessment' },
      { index: 9, name: 'Consent Mechanism Evaluation' },
      { index: 10, name: 'Data Minimization Compliance' },
      { index: 11, name: 'Purpose Limitation Check' },
      { index: 12, name: 'Storage Limitation Compliance' },
      { index: 13, name: 'Access Control Effectiveness' },
      { index: 14, name: 'Encryption at Rest and Transit' },
      { index: 15, name: 'Privacy by Design Assessment' },
      { index: 16, name: 'Third-Party Data Sharing Audit' },
      { index: 17, name: 'Privacy Training Effectiveness' },
      { index: 18, name: 'Privacy Incident Response' },
      { index: 19, name: 'Privacy Technology Stack Review' },
      { index: 20, name: 'Privacy Maturity Score' },
    ],
  },
  {
    categoryKey: 'long-term-risk-ai',
    categoryName: 'Long-Term Risk AI',
    description: 'Assess long-term risks and existential considerations',
    analysisTypes: [
      { index: 1, name: 'Capability Progression Analysis' },
      { index: 2, name: 'Alignment Assessment' },
      { index: 3, name: 'Goal Stability Verification' },
      { index: 4, name: 'Corrigibility Assessment' },
      { index: 5, name: 'Value Lock-In Risk' },
      { index: 6, name: 'Emergent Behavior Detection' },
      { index: 7, name: 'Systemic Risk Assessment' },
      { index: 8, name: 'Concentration of Power Analysis' },
      { index: 9, name: 'Dual-Use Risk Evaluation' },
      { index: 10, name: 'Technological Unemployment Impact' },
      { index: 11, name: 'Weaponization Risk Assessment' },
      { index: 12, name: 'Dependency Risk Analysis' },
      { index: 13, name: 'Cascading Failure Scenarios' },
      { index: 14, name: 'Recovery Plan Assessment' },
      { index: 15, name: 'International Governance Alignment' },
      { index: 16, name: 'Research Safety Practices' },
      { index: 17, name: 'Multi-Stakeholder Risk Sharing' },
      { index: 18, name: 'Scenario Planning Completeness' },
      { index: 19, name: 'Risk Communication Effectiveness' },
      { index: 20, name: 'Long-Term Risk Maturity Score' },
    ],
  },
  {
    categoryKey: 'environmental-impact-ai',
    categoryName: 'Environmental Impact AI',
    description: 'Measure and mitigate environmental impact of AI systems',
    analysisTypes: [
      { index: 1, name: 'Training Carbon Footprint' },
      { index: 2, name: 'Inference Carbon Footprint' },
      { index: 3, name: 'Data Center Energy Source' },
      { index: 4, name: 'Hardware Lifecycle Assessment' },
      { index: 5, name: 'Cooling System Efficiency' },
      { index: 6, name: 'Network Energy Consumption' },
      { index: 7, name: 'Storage Environmental Impact' },
      { index: 8, name: 'Model Size vs Accuracy Trade-off' },
      { index: 9, name: 'Pruning and Distillation Usage' },
      { index: 10, name: 'Batch Processing Efficiency' },
      { index: 11, name: 'Auto-Scaling Effectiveness' },
      { index: 12, name: 'Renewable Energy Commitment' },
      { index: 13, name: 'Carbon Offset Quality' },
      { index: 14, name: 'Environmental Reporting Accuracy' },
      { index: 15, name: 'Supply Chain Environmental Audit' },
      { index: 16, name: 'Waste Reduction Initiatives' },
      { index: 17, name: 'Water Usage Assessment' },
      { index: 18, name: 'Biodiversity Impact Consideration' },
      { index: 19, name: 'Environmental Policy Compliance' },
      { index: 20, name: 'Environmental Impact Maturity Score' },
    ],
  },
  {
    categoryKey: 'ethical-ai',
    categoryName: 'Ethical AI',
    description: 'Evaluate ethical considerations in AI development and deployment',
    analysisTypes: [
      { index: 1, name: 'Ethical Framework Adoption' },
      { index: 2, name: 'Informed Consent Practices' },
      { index: 3, name: 'Beneficence Assessment' },
      { index: 4, name: 'Non-Maleficence Verification' },
      { index: 5, name: 'Justice and Equity Review' },
      { index: 6, name: 'Autonomy Respect Assessment' },
      { index: 7, name: 'Dignity Preservation Check' },
      { index: 8, name: 'Truthfulness and Honesty' },
      { index: 9, name: 'Ethical Review Board Status' },
      { index: 10, name: 'Whistleblower Protection' },
      { index: 11, name: 'Ethical Training Coverage' },
      { index: 12, name: 'Moral Responsibility Attribution' },
      { index: 13, name: 'Dual-Use Ethics Assessment' },
      { index: 14, name: 'Vulnerable Population Protection' },
      { index: 15, name: 'Ethical Impact Measurement' },
      { index: 16, name: 'Ethics in Data Collection' },
      { index: 17, name: 'Ethics in Model Design' },
      { index: 18, name: 'Ethics in Deployment' },
      { index: 19, name: 'Ethical Incident Response' },
      { index: 20, name: 'Ethical AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'sensitivity-analysis-ai',
    categoryName: 'Sensitivity Analysis AI',
    description: 'Assess model sensitivity to inputs and parameters',
    analysisTypes: [
      { index: 1, name: 'Input Perturbation Analysis' },
      { index: 2, name: 'Feature Sensitivity Ranking' },
      { index: 3, name: 'Hyperparameter Sensitivity' },
      { index: 4, name: 'Data Size Sensitivity' },
      { index: 5, name: 'Noise Robustness Testing' },
      { index: 6, name: 'Boundary Value Analysis' },
      { index: 7, name: 'One-at-a-Time Sensitivity' },
      { index: 8, name: 'Global Sensitivity Analysis' },
      { index: 9, name: 'Sobol Index Computation' },
      { index: 10, name: 'Morris Method Application' },
      { index: 11, name: 'Monte Carlo Simulation' },
      { index: 12, name: 'Variance-Based Analysis' },
      { index: 13, name: 'Correlation Analysis' },
      { index: 14, name: 'Threshold Sensitivity' },
      { index: 15, name: 'Time Sensitivity Analysis' },
      { index: 16, name: 'Multi-Objective Sensitivity' },
      { index: 17, name: 'Uncertainty Propagation' },
      { index: 18, name: 'Sensitivity Visualization Quality' },
      { index: 19, name: 'Automated Sensitivity Testing' },
      { index: 20, name: 'Sensitivity Analysis Maturity Score' },
    ],
  },
  {
    categoryKey: 'governance-ai',
    categoryName: 'Governance AI',
    description: 'Evaluate AI governance structures and policies',
    analysisTypes: [
      { index: 1, name: 'Governance Framework Assessment' },
      { index: 2, name: 'Policy Documentation Quality' },
      { index: 3, name: 'Roles and Responsibilities Clarity' },
      { index: 4, name: 'Decision-Making Process' },
      { index: 5, name: 'Risk Management Framework' },
      { index: 6, name: 'Approval Workflow Effectiveness' },
      { index: 7, name: 'Change Management Process' },
      { index: 8, name: 'Stakeholder Engagement Quality' },
      { index: 9, name: 'Communication Strategy' },
      { index: 10, name: 'Training and Awareness Programs' },
      { index: 11, name: 'Monitoring and Reporting' },
      { index: 12, name: 'Incident Management Process' },
      { index: 13, name: 'Continuous Improvement Cycle' },
      { index: 14, name: 'Cross-Functional Coordination' },
      { index: 15, name: 'Board-Level AI Oversight' },
      { index: 16, name: 'External Advisory Engagement' },
      { index: 17, name: 'Governance Tool Effectiveness' },
      { index: 18, name: 'Benchmarking Against Standards' },
      { index: 19, name: 'Governance Budget Allocation' },
      { index: 20, name: 'Governance Maturity Score' },
    ],
  },
  {
    categoryKey: 'secure-ai',
    categoryName: 'Secure AI',
    description: 'Evaluate security measures protecting AI systems',
    analysisTypes: [
      { index: 1, name: 'Model Security Assessment' },
      { index: 2, name: 'Data Security Audit' },
      { index: 3, name: 'API Security Testing' },
      { index: 4, name: 'Access Control Review' },
      { index: 5, name: 'Authentication Mechanism Audit' },
      { index: 6, name: 'Encryption Standard Compliance' },
      { index: 7, name: 'Adversarial Attack Resistance' },
      { index: 8, name: 'Model Extraction Prevention' },
      { index: 9, name: 'Data Poisoning Detection' },
      { index: 10, name: 'Backdoor Detection Analysis' },
      { index: 11, name: 'Supply Chain Security' },
      { index: 12, name: 'Infrastructure Security' },
      { index: 13, name: 'Network Security Assessment' },
      { index: 14, name: 'Vulnerability Scanning Coverage' },
      { index: 15, name: 'Penetration Testing Frequency' },
      { index: 16, name: 'Security Incident Response Plan' },
      { index: 17, name: 'Security Monitoring Effectiveness' },
      { index: 18, name: 'Security Training Coverage' },
      { index: 19, name: 'Compliance with Security Standards' },
      { index: 20, name: 'Security Maturity Score' },
    ],
  },
  {
    categoryKey: 'energy-efficient-ai',
    categoryName: 'Energy-Efficient AI',
    description: 'Assess energy efficiency of AI training and inference',
    analysisTypes: [
      { index: 1, name: 'FLOPs per Prediction Analysis' },
      { index: 2, name: 'Training Energy Budget' },
      { index: 3, name: 'Inference Latency vs Energy' },
      { index: 4, name: 'Model Compression Ratio' },
      { index: 5, name: 'Quantization Effectiveness' },
      { index: 6, name: 'Knowledge Distillation Usage' },
      { index: 7, name: 'Pruning Efficiency' },
      { index: 8, name: 'Hardware Accelerator Utilization' },
      { index: 9, name: 'Batch Size Optimization' },
      { index: 10, name: 'Mixed Precision Training' },
      { index: 11, name: 'Gradient Checkpointing' },
      { index: 12, name: 'Early Stopping Effectiveness' },
      { index: 13, name: 'Transfer Learning Usage' },
      { index: 14, name: 'Architecture Search Efficiency' },
      { index: 15, name: 'Idle Resource Detection' },
      { index: 16, name: 'Scheduling Optimization' },
      { index: 17, name: 'Energy Monitoring Tools' },
      { index: 18, name: 'Energy Efficiency Maturity Score' },
    ],
  },
  {
    categoryKey: 'hallucination-prevention-ai',
    categoryName: 'Hallucination Prevention AI',
    description: 'Evaluate measures to prevent and detect AI hallucinations',
    analysisTypes: [
      { index: 1, name: 'Factual Grounding Assessment' },
      { index: 2, name: 'Source Verification Pipeline' },
      { index: 3, name: 'Retrieval Augmentation Quality' },
      { index: 4, name: 'Confidence Calibration' },
      { index: 5, name: 'Contradiction Detection' },
      { index: 6, name: 'Knowledge Boundary Awareness' },
      { index: 7, name: 'Uncertainty Expression Quality' },
      { index: 8, name: 'Citation Generation Accuracy' },
      { index: 9, name: 'Claim Verification Pipeline' },
      { index: 10, name: 'Human Fact-Checking Integration' },
      { index: 11, name: 'Domain-Specific Accuracy' },
      { index: 12, name: 'Temporal Knowledge Currency' },
      { index: 13, name: 'Multi-Source Verification' },
      { index: 14, name: 'Hallucination Detection Rate' },
      { index: 15, name: 'False Positive Rate' },
      { index: 16, name: 'User Correction Mechanism' },
      { index: 17, name: 'Training Data Quality Control' },
      { index: 18, name: 'Guardrail Effectiveness' },
      { index: 19, name: 'Hallucination Monitoring Dashboard' },
      { index: 20, name: 'Hallucination Prevention Maturity Score' },
    ],
  },
  {
    categoryKey: 'hypothesis-ai',
    categoryName: 'Hypothesis AI',
    description: 'Evaluate hypothesis testing and validation in AI experiments',
    analysisTypes: [
      { index: 1, name: 'Hypothesis Formulation Quality' },
      { index: 2, name: 'Experimental Design Assessment' },
      { index: 3, name: 'Control Group Adequacy' },
      { index: 4, name: 'Sample Size Sufficiency' },
      { index: 5, name: 'Statistical Power Analysis' },
      { index: 6, name: 'P-Value Interpretation' },
      { index: 7, name: 'Effect Size Reporting' },
      { index: 8, name: 'Confidence Interval Analysis' },
      { index: 9, name: 'Multiple Testing Correction' },
      { index: 10, name: 'Bayesian vs Frequentist Approach' },
      { index: 11, name: 'Reproducibility Verification' },
      { index: 12, name: 'Pre-Registration Practice' },
      { index: 13, name: 'Publication Bias Awareness' },
      { index: 14, name: 'Null Result Documentation' },
      { index: 15, name: 'Meta-Analysis Integration' },
      { index: 16, name: 'Cross-Validation Strategy' },
      { index: 17, name: 'Ablation Study Completeness' },
      { index: 18, name: 'Hypothesis Revision Protocol' },
      { index: 19, name: 'Experiment Tracking Tools' },
      { index: 20, name: 'Hypothesis Testing Maturity Score' },
    ],
  },
  {
    categoryKey: 'threat-ai',
    categoryName: 'Threat AI',
    description: 'Assess threat modeling and risk analysis for AI systems',
    analysisTypes: [
      { index: 1, name: 'Threat Landscape Mapping' },
      { index: 2, name: 'Attack Surface Analysis' },
      { index: 3, name: 'STRIDE Threat Modeling' },
      { index: 4, name: 'MITRE ATLAS Alignment' },
      { index: 5, name: 'Adversarial ML Threat Assessment' },
      { index: 6, name: 'Data Poisoning Risk' },
      { index: 7, name: 'Model Inversion Attack Risk' },
      { index: 8, name: 'Membership Inference Risk' },
      { index: 9, name: 'Evasion Attack Resilience' },
      { index: 10, name: 'Prompt Injection Risk' },
      { index: 11, name: 'Supply Chain Threat Analysis' },
      { index: 12, name: 'Insider Threat Assessment' },
      { index: 13, name: 'Social Engineering Risk' },
      { index: 14, name: 'API Abuse Detection' },
      { index: 15, name: 'Denial of Service Protection' },
      { index: 16, name: 'Threat Intelligence Integration' },
      { index: 17, name: 'Red Team Exercise Results' },
      { index: 18, name: 'Threat Response Playbooks' },
      { index: 19, name: 'Threat Monitoring Coverage' },
      { index: 20, name: 'Threat AI Maturity Score' },
    ],
  },
  {
    categoryKey: 'fine-tuning-analysis',
    categoryName: 'Fine-Tuning Analysis',
    description: 'Evaluate fine-tuning practices and effectiveness',
    analysisTypes: [
      { index: 1, name: 'Base Model Selection Criteria' },
      { index: 2, name: 'Training Data Quality Assessment' },
      { index: 3, name: 'Data Curation Pipeline' },
      { index: 4, name: 'Hyperparameter Optimization' },
      { index: 5, name: 'Learning Rate Schedule Analysis' },
      { index: 6, name: 'Catastrophic Forgetting Prevention' },
      { index: 7, name: 'LoRA/PEFT Effectiveness' },
      { index: 8, name: 'Full Fine-Tune vs Adapter Analysis' },
      { index: 9, name: 'Evaluation Metric Selection' },
      { index: 10, name: 'Benchmark Performance Tracking' },
      { index: 11, name: 'Overfitting Detection' },
      { index: 12, name: 'Generalization Testing' },
      { index: 13, name: 'Domain Adaptation Quality' },
      { index: 14, name: 'Instruction Tuning Effectiveness' },
      { index: 15, name: 'RLHF Implementation Quality' },
      { index: 16, name: 'Alignment Verification' },
      { index: 17, name: 'Cost-Performance Analysis' },
      { index: 18, name: 'Reproducibility of Results' },
      { index: 19, name: 'Model Card Documentation' },
      { index: 20, name: 'Fine-Tuning Maturity Score' },
    ],
  },
  {
    categoryKey: 'interpretability-ai',
    categoryName: 'Interpretability AI',
    description: 'Deep interpretability analysis of model internals',
    analysisTypes: [
      { index: 1, name: 'Neuron Activation Analysis' },
      { index: 2, name: 'Layer-wise Relevance Propagation' },
      { index: 3, name: 'Gradient-based Attribution' },
      { index: 4, name: 'Attention Pattern Analysis' },
      { index: 5, name: 'Concept Activation Vectors' },
      { index: 6, name: 'Probing Classifier Results' },
      { index: 7, name: 'Circuit Discovery Analysis' },
      { index: 8, name: 'Representation Similarity' },
      { index: 9, name: 'Disentanglement Metrics' },
      { index: 10, name: 'Sparse Autoencoder Analysis' },
      { index: 11, name: 'Feature Visualization Quality' },
      { index: 12, name: 'Semantic Space Mapping' },
      { index: 13, name: 'Decision Boundary Visualization' },
      { index: 14, name: 'Embedding Space Analysis' },
      { index: 15, name: 'Information Flow Tracking' },
      { index: 16, name: 'Modular Decomposition' },
      { index: 17, name: 'Interpretability Tool Coverage' },
      { index: 18, name: 'Interpretability Maturity Score' },
    ],
  },
];

export function seedAnalysisFrameworks() {
  const existing = db.select().from(analysisFrameworks).all();
  if (existing.length > 0) {
    console.log(`Analysis frameworks already seeded (${existing.length} found). Skipping.`);
    return;
  }

  for (let i = 0; i < frameworks.length; i++) {
    const fw = frameworks[i];
    db.insert(analysisFrameworks)
      .values({
        id: randomUUID(),
        categoryKey: fw.categoryKey,
        categoryName: fw.categoryName,
        description: fw.description,
        analysisTypes: JSON.stringify(fw.analysisTypes),
        totalItems: fw.analysisTypes.length,
        sortOrder: i + 1,
        createdAt: new Date(),
      })
      .run();
  }
  console.log(`Seeded ${frameworks.length} analysis frameworks.`);
}

// Allow running directly: npx tsx lib/db/seed-analysis-frameworks.ts
if (require.main === module) {
  seedAnalysisFrameworks();
}
