sonar.projectKey=talentshill
sonar.organization=praveenasthana123
sonar.projectName=TalentsHill Portal
sonar.sources=app,features,lib,jobs,components
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/drizzle/**,**/.next/**,**/out/**
sonar.tests=tests
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
