"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";

/* ─── Signal Modalities ─── */
const modalities = [
  {
    id: "eeg",
    name: "EEG (Electroencephalography)",
    tagline: "Non-invasive cortical electrical activity",
    color: "from-blue-500 to-indigo-600",
    accent: "text-blue-400",
    bgAccent: "bg-blue-500/10",
    borderAccent: "border-blue-500/30",
    description:
      "Measures voltage fluctuations from neuronal ionic currents on the scalp surface. The gold standard for real-time, portable BCI due to high temporal resolution (ms-scale) and non-invasive nature.",
    specs: {
      "Temporal Resolution": "~1 ms",
      "Spatial Resolution": "~10 mm (scalp)",
      "Frequency Bands": "Delta (0.5-4 Hz), Theta (4-8), Alpha (8-13), Beta (13-30), Gamma (30-100+)",
      "Portability": "High — dry/wet electrode caps, wireless headsets",
      "Cost": "Low-Medium ($200 consumer to $50K clinical)",
    },
    electrode_systems: [
      {
        name: "10-20 International System",
        description: "Standard 21-electrode placement based on skull landmarks (nasion, inion, preauricular points). Electrodes named by brain region (F=frontal, C=central, P=parietal, O=occipital, T=temporal) + hemisphere number (odd=left, even=right, z=midline).",
        positions: ["Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8", "T3", "C3", "Cz", "C4", "T4", "T5", "P3", "Pz", "P4", "T6", "O1", "Oz", "O2", "A1/A2 (ref)"],
      },
      {
        name: "10-10 Extended System",
        description: "Extended 64-75 electrode system for higher spatial resolution. Subdivides 10-20 positions by 10% increments. Used in research-grade EEG and source localization studies.",
        positions: ["FC1", "FC2", "FC5", "FC6", "CP1", "CP2", "CP5", "CP6", "AF3", "AF4", "PO3", "PO4", "FT7", "FT8", "TP7", "TP8", "...64-75 total"],
      },
      {
        name: "10-5 High-Density System",
        description: "128-256 electrode dense array for precise source localization and cortical mapping. Used in clinical epilepsy monitoring and advanced BCI research.",
        positions: ["128 / 256 channels", "Geodesic sensor net", "< 5% inter-electrode spacing", "Full scalp coverage"],
      },
    ],
    signal_features: [
      { name: "P300 ERP", description: "Event-related potential ~300ms post-stimulus. Used in P300 spellers (e.g., BCI2000).", application: "Spelling, selection, lie detection" },
      { name: "SSVEP", description: "Steady-state visually evoked potential — frequency-tagged visual stimulation.", application: "Fast BCI control, wheelchair navigation" },
      { name: "Motor Imagery (MI)", description: "Sensorimotor rhythm (mu/beta) changes during imagined movement.", application: "Prosthetic control, cursor movement, neurorehab" },
      { name: "Error-Related Potential (ErrP)", description: "Negative deflection when user detects an error in BCI output.", application: "Self-correcting BCI, adaptive systems" },
      { name: "Alpha Asymmetry", description: "Frontal alpha power difference between hemispheres.", application: "Emotion detection, meditation feedback, depression biomarker" },
      { name: "Seizure Patterns", description: "Epileptiform spikes, sharp waves, and rhythmic discharges.", application: "Epilepsy diagnosis, seizure prediction" },
    ],
    hardware: [
      { name: "OpenBCI Cyton/Ganglion", type: "Research open-source", channels: "8-16 ch", detail: "ADS1299 AFE, open-source firmware, BLE/Wi-Fi" },
      { name: "g.tec g.USBamp / g.Nautilus", type: "Clinical-grade", channels: "16-64 ch", detail: "Active electrodes, 24-bit ADC, high CMRR" },
      { name: "Emotiv EPOC X / Insight", type: "Consumer/Research", channels: "5-14 ch", detail: "Saline felt sensors, BLE, cloud analytics" },
      { name: "NeuroSky MindWave", type: "Consumer", channels: "1 ch", detail: "Dry electrode, TGAM ASIC, attention/meditation metrics" },
      { name: "Brain Products actiCHamp", type: "Research-grade", channels: "32-160 ch", detail: "Active shielding, 24-bit, <1 µV noise, BrainVision" },
      { name: "ANT Neuro eego", type: "Clinical-research", channels: "32-256 ch", detail: "Waveguard cap, EEProbe software, high-density" },
      { name: "Muse 2 / Muse S", type: "Consumer wellness", channels: "4-7 ch", detail: "Dry electrode headband, meditation app, PPG + gyro" },
      { name: "Neuracle NeuSen W", type: "Wireless research", channels: "32-64 ch", detail: "Wireless, wet/dry, high-impedance, <0.5 µV noise" },
    ],
  },
  {
    id: "emg",
    name: "EMG (Electromyography)",
    tagline: "Muscle electrical activity & motor intent",
    color: "from-emerald-500 to-green-600",
    accent: "text-emerald-400",
    bgAccent: "bg-emerald-500/10",
    borderAccent: "border-emerald-500/30",
    description:
      "Records electrical signals generated by skeletal muscle contraction. Surface EMG (sEMG) is non-invasive; intramuscular EMG uses needle electrodes for individual motor unit analysis. Critical for prosthetic control and gesture recognition.",
    specs: {
      "Temporal Resolution": "~1 ms",
      "Spatial Resolution": "Individual muscles (sEMG) / motor units (needle)",
      "Frequency Range": "20-500 Hz (sEMG), 10 Hz-10 kHz (needle)",
      "Portability": "High — armband, patch, or sleeve form factors",
      "Cost": "Low-Medium ($100 consumer to $20K clinical)",
    },
    signal_features: [
      { name: "RMS Amplitude", description: "Root-mean-square envelope of EMG burst — correlates with muscle force.", application: "Proportional prosthetic control" },
      { name: "Mean/Median Frequency", description: "Spectral shift indicates muscle fatigue over time.", application: "Ergonomic assessment, sports science" },
      { name: "Motor Unit Action Potentials", description: "Individual MU firing patterns (needle EMG).", application: "Neuromuscular diagnosis (ALS, neuropathy)" },
      { name: "Gesture Classification", description: "Pattern recognition on multi-channel sEMG for hand gestures.", application: "Prosthetic hands, sign language, VR input" },
      { name: "Force Estimation", description: "Mapping EMG amplitude to joint torque using musculoskeletal models.", application: "Exoskeleton control, rehab robotics" },
    ],
    hardware: [
      { name: "Delsys Trigno / Avanti", type: "Clinical-research", channels: "16-48 ch", detail: "Wireless sEMG + IMU, 2000 Hz, SDK available" },
      { name: "Myo Armband (Thalmic)", type: "Consumer gesture", channels: "8 ch", detail: "Forearm sEMG, IMU, BLE, gesture API (discontinued but cloned)" },
      { name: "OTBioelettronica Quattrocento", type: "HD-sEMG research", channels: "Up to 400 ch", detail: "High-density grid arrays, motor unit decomposition" },
      { name: "BioSignalsPlux (PLUX)", type: "Wearable research", channels: "1-8 ch", detail: "BLE, multi-sensor (EMG + EDA + ECG), Python API" },
      { name: "Myomo MyoPro", type: "Rehab device", channels: "2-4 ch", detail: "Powered arm orthosis controlled by residual EMG" },
      { name: "CTRL-Labs (Meta) wristband", type: "Neural input", channels: "16 ch", detail: "High-density wrist EMG, AI gesture decode (research)" },
    ],
  },
  {
    id: "fmri",
    name: "fMRI (Functional MRI)",
    tagline: "Blood-oxygen-level-dependent brain imaging",
    color: "from-violet-500 to-purple-600",
    accent: "text-violet-400",
    bgAccent: "bg-violet-500/10",
    borderAccent: "border-violet-500/30",
    description:
      "Detects changes in blood oxygenation (BOLD signal) as a proxy for neural activity. Provides millimeter-level spatial resolution across the whole brain. The gold standard for brain mapping and cognitive neuroscience, though limited by low temporal resolution and non-portability.",
    specs: {
      "Temporal Resolution": "~1-2 seconds (hemodynamic delay)",
      "Spatial Resolution": "~1-3 mm (voxel size)",
      "Field Strength": "1.5T, 3T (clinical), 7T+ (research)",
      "Portability": "None — large superconducting magnet",
      "Cost": "High ($1M-$5M+ system, $500-$2K/session)",
    },
    signal_features: [
      { name: "BOLD Contrast", description: "Oxy/deoxy-hemoglobin ratio changes reflecting neural metabolic demand.", application: "Whole-brain activity mapping" },
      { name: "Resting-State Networks", description: "Intrinsic connectivity networks (default mode, salience, executive).", application: "Brain connectivity analysis, clinical biomarkers" },
      { name: "Task-Based Activation", description: "Voxel-wise statistical maps of task-related BOLD changes.", application: "Motor/language mapping, pre-surgical planning" },
      { name: "Multivariate Pattern Analysis (MVPA)", description: "Machine learning on voxel patterns to decode cognitive states.", application: "Brain reading, thought decoding, BCI research" },
      { name: "Real-Time fMRI Neurofeedback", description: "Closed-loop feedback of brain activity to the subject in near-real-time.", application: "Neurorehab, pain management, emotion regulation" },
    ],
    hardware: [
      { name: "Siemens MAGNETOM Prisma", type: "3T research", channels: "64-ch head coil", detail: "80 mT/m gradients, simultaneous multi-slice" },
      { name: "Siemens MAGNETOM Terra", type: "7T ultra-high-field", channels: "32-ch head coil", detail: "Sub-millimeter resolution, laminar fMRI" },
      { name: "GE SIGNA Premier", type: "3T clinical-research", channels: "48-ch coil", detail: "AIR coils, HyperBand acceleration" },
      { name: "Philips Ingenia Ambition", type: "1.5T helium-free", channels: "32-ch coil", detail: "Fully sealed magnet, low operating cost" },
      { name: "Hyperfine Swoop", type: "0.064T portable", channels: "Low-field", detail: "Bedside MRI, point-of-care neuroimaging" },
    ],
  },
  {
    id: "mri-structural",
    name: "MRI (Structural / Diffusion)",
    tagline: "High-resolution brain anatomy & white matter",
    color: "from-pink-500 to-rose-600",
    accent: "text-pink-400",
    bgAccent: "bg-pink-500/10",
    borderAccent: "border-pink-500/30",
    description:
      "Structural MRI provides high-resolution anatomical images of brain tissue. Diffusion MRI (DTI/HARDI) maps white matter fiber tracts by tracking water diffusion. Essential for surgical planning, brain morphometry, and connectome mapping.",
    specs: {
      "Temporal Resolution": "Minutes (full volume scan)",
      "Spatial Resolution": "~0.5-1 mm isotropic",
      "Sequences": "T1w, T2w, FLAIR, DWI, DTI, SWI, MRA",
      "Portability": "None (same hardware as fMRI)",
      "Cost": "Same scanner as fMRI — $500-$2K/session",
    },
    signal_features: [
      { name: "T1-Weighted", description: "High gray/white matter contrast for anatomical segmentation.", application: "Brain morphometry, cortical thickness, VBM" },
      { name: "T2-FLAIR", description: "CSF-suppressed imaging highlighting lesions and edema.", application: "MS lesion detection, stroke, tumor delineation" },
      { name: "Diffusion Tensor Imaging (DTI)", description: "Maps fractional anisotropy (FA) and mean diffusivity (MD) of white matter.", application: "Tractography, connectome, TBI assessment" },
      { name: "Susceptibility-Weighted (SWI)", description: "Detects microbleeds, iron deposits, and venous structures.", application: "TBI grading, neurodegenerative disease" },
      { name: "MR Angiography (MRA)", description: "Non-contrast or contrast-enhanced vascular imaging.", application: "Aneurysm screening, AVM detection" },
    ],
    hardware: [
      { name: "Same MRI scanners as fMRI", type: "1.5T / 3T / 7T", channels: "Multi-channel coils", detail: "Different pulse sequences, same hardware platform" },
    ],
  },
  {
    id: "fnirs",
    name: "fNIRS (Functional Near-Infrared)",
    tagline: "Optical brain imaging — portable & wearable",
    color: "from-orange-500 to-amber-600",
    accent: "text-orange-400",
    bgAccent: "bg-orange-500/10",
    borderAccent: "border-orange-500/30",
    description:
      "Uses near-infrared light (650-950 nm) to measure cortical hemodynamic changes through the skull. A portable, wearable alternative to fMRI with moderate spatial resolution. Tolerant to motion artifacts — ideal for naturalistic and infant studies.",
    specs: {
      "Temporal Resolution": "~100 ms (sampling), ~5 s (hemodynamic)",
      "Spatial Resolution": "~10-30 mm (cortical surface only)",
      "Wavelengths": "~760 nm (deoxy-Hb) and ~850 nm (oxy-Hb)",
      "Portability": "High — headband / cap form factor, wireless",
      "Cost": "Medium ($10K-$100K research, $500-$2K consumer)",
    },
    signal_features: [
      { name: "Oxy-Hb / Deoxy-Hb", description: "Separate chromophore concentration changes via modified Beer-Lambert law.", application: "Cortical activation mapping" },
      { name: "Prefrontal Activity", description: "PFC oxygenation during cognitive tasks.", application: "Cognitive load, attention, neuromarketing" },
      { name: "Motor Cortex Mapping", description: "Hemodynamic changes during movement or motor imagery.", application: "BCI, neurorehab, prosthetic control" },
      { name: "Hyperscanning", description: "Simultaneous multi-brain fNIRS for social interaction studies.", application: "Social neuroscience, team dynamics" },
    ],
    hardware: [
      { name: "NIRx NIRSport2", type: "Wireless research", channels: "8-64 ch", detail: "Wearable, wireless, BrainVision compatible" },
      { name: "Artinis Brite / OctaMon", type: "Portable research", channels: "8-27 ch", detail: "Lightweight, motion-tolerant, Bluetooth" },
      { name: "Kernel Flow", type: "Next-gen wearable", channels: "52 modules (3000+ channels)", detail: "TD-fNIRS, modular helmet, high-density" },
      { name: "Hitachi ETG-4000", type: "Clinical", channels: "24-52 ch", detail: "Continuous-wave, pediatric & adult caps" },
      { name: "Mendi", type: "Consumer neurofeedback", channels: "2 ch", detail: "Prefrontal fNIRS headband, app-guided training" },
    ],
  },
  {
    id: "ecog",
    name: "ECoG & Invasive BCI",
    tagline: "Direct cortical recording — highest fidelity",
    color: "from-red-600 to-red-800",
    accent: "text-red-400",
    bgAccent: "bg-red-500/10",
    borderAccent: "border-red-500/30",
    description:
      "Electrocorticography (ECoG) places electrode arrays directly on the cortical surface (subdural) or penetrates cortex (Utah array). Provides orders of magnitude better signal quality than EEG. Used in clinical epilepsy surgery and cutting-edge BCI implants (Neuralink, BrainGate, Stentrode).",
    specs: {
      "Temporal Resolution": "< 1 ms",
      "Spatial Resolution": "~1 mm (ECoG grid), ~50 µm (Utah array)",
      "Frequency Range": "0.1 Hz - 500 Hz+ (high-gamma accessible)",
      "Portability": "Implanted — fully portable once implanted",
      "Cost": "Very high (surgical + device: $50K-$500K+)",
    },
    signal_features: [
      { name: "High-Gamma Activity (70-150 Hz)", description: "Focal cortical processing invisible to scalp EEG.", application: "Fine motor decode, speech BCI" },
      { name: "Single-Unit Spikes", description: "Individual neuron firing (intracortical arrays only).", application: "BrainGate cursor control, robotic arm BCI" },
      { name: "Local Field Potentials (LFP)", description: "Population-level synaptic activity from penetrating electrodes.", application: "Movement intention decode, closed-loop DBS" },
      { name: "Speech Decoding", description: "Decoding attempted speech from sensorimotor cortex ECoG.", application: "Speech neuroprosthesis for paralyzed patients" },
    ],
    hardware: [
      { name: "Neuralink N1 Implant", type: "Intracortical", channels: "1024 electrodes", detail: "Wireless, 6144 Hz sampling, surgical robot insertion" },
      { name: "BrainGate (Utah Array)", type: "Intracortical", channels: "96-ch silicon array", detail: "10x10 electrode grid, 1 mm penetration depth" },
      { name: "Synchron Stentrode", type: "Endovascular", channels: "16 ch", detail: "Stent-mounted electrodes, no open-brain surgery" },
      { name: "Ad-Tech / PMT ECoG Grids", type: "Subdural clinical", channels: "16-256 ch", detail: "Silicone grid/strip, clinical epilepsy monitoring" },
      { name: "Blackrock Microsystems", type: "Research intracortical", channels: "96-256 ch", detail: "Cerebus/Neuroport, single-unit recording" },
    ],
  },
];

/* ─── BCI Processing Pipeline ─── */
const pipeline = [
  {
    id: "acquisition",
    title: "Signal Acquisition",
    icon: "📡",
    color: "from-blue-500 to-indigo-600",
    steps: [
      "Electrode placement (10-20 / 10-10 / custom montage)",
      "Impedance check & signal quality verification",
      "Analog front-end (ADS1299, RHD2000) amplification",
      "ADC sampling (256 Hz - 30 kHz depending on modality)",
      "Wireless/wired data streaming (LSL, BLE, USB)",
    ],
  },
  {
    id: "preprocessing",
    title: "Preprocessing",
    icon: "🧹",
    color: "from-cyan-500 to-teal-600",
    steps: [
      "Band-pass filtering (0.5-100 Hz EEG, 20-500 Hz EMG)",
      "Notch filter (50/60 Hz power line removal)",
      "Artifact rejection (EOG, EMG, motion) — ICA / ASR",
      "Re-referencing (common average, Laplacian, bipolar)",
      "Epoch segmentation & baseline correction",
    ],
  },
  {
    id: "features",
    title: "Feature Extraction",
    icon: "🔬",
    color: "from-violet-500 to-purple-600",
    steps: [
      "Time-domain: variance, RMS, Hjorth parameters",
      "Frequency-domain: PSD, band power (alpha, beta, mu, gamma)",
      "Time-frequency: wavelets, STFT, Hilbert transform",
      "Spatial: CSP (Common Spatial Patterns), source localization",
      "Connectivity: coherence, phase-locking value, Granger causality",
    ],
  },
  {
    id: "classification",
    title: "Classification / Decoding",
    icon: "🧠",
    color: "from-orange-500 to-red-600",
    steps: [
      "Classical ML: LDA, SVM, Random Forest",
      "Deep learning: EEGNet, ShallowConvNet, DeepConvNet",
      "Transfer learning & domain adaptation across subjects",
      "Recurrent models (LSTM/GRU) for temporal dynamics",
      "Reinforcement learning for adaptive BCI",
    ],
  },
  {
    id: "feedback",
    title: "Feedback & Control",
    icon: "🎯",
    color: "from-emerald-500 to-green-600",
    steps: [
      "Real-time output mapping (cursor, wheelchair, prosthetic)",
      "Neurofeedback display (visual, auditory, haptic)",
      "Closed-loop stimulation (tDCS, TMS, DBS triggered by decode)",
      "Latency optimization (< 200 ms end-to-end target)",
      "User adaptation & co-adaptive calibration",
    ],
  },
  {
    id: "application",
    title: "Application Layer",
    icon: "🚀",
    color: "from-pink-500 to-rose-600",
    steps: [
      "Communication (P300 speller, imagined speech)",
      "Motor restoration (robotic arm, exoskeleton, FES)",
      "Neurorehabilitation (stroke recovery, neuroplasticity)",
      "Cognitive assessment (attention, workload, drowsiness)",
      "Entertainment & wellness (meditation, neurogaming)",
    ],
  },
];

/* ─── BCI Services ─── */
const bciServices = [
  {
    id: "headset-design",
    title: "BCI Headset / Electrode Design",
    tagline: "Custom hardware for your neuro application",
    color: "from-blue-500 to-indigo-600",
    deliverables: ["Electrode array design (dry/wet/hybrid)", "Headset mechanical design (3D printed / injection mold)", "Analog front-end PCB (ADS1299 / RHD2000 based)", "BLE / Wi-Fi streaming firmware", "Impedance monitoring circuit"],
  },
  {
    id: "signal-processing",
    title: "Signal Processing & Algorithm",
    tagline: "From raw signals to actionable features",
    color: "from-violet-500 to-purple-600",
    deliverables: ["Custom preprocessing pipeline (Python / C++)", "Feature extraction library (CSP, PSD, wavelets)", "Real-time artifact rejection (ICA / ASR)", "Source localization (eLORETA, beamforming)", "Signal quality scoring algorithm"],
  },
  {
    id: "ml-decode",
    title: "ML / AI Decoder Development",
    tagline: "Train and deploy neural decoders",
    color: "from-orange-500 to-red-600",
    deliverables: ["Subject-specific & cross-subject models", "EEGNet / ShallowConvNet architecture tuning", "Transfer learning pipeline for new users", "Real-time inference engine (TFLite / ONNX)", "Model evaluation dashboard (accuracy, ITR, confusion)"],
  },
  {
    id: "neurofeedback",
    title: "Neurofeedback Platform",
    tagline: "Closed-loop brain training systems",
    color: "from-emerald-500 to-green-600",
    deliverables: ["Real-time feedback engine (visual / auditory / haptic)", "Session protocol designer & scheduler", "Progress tracking & analytics dashboard", "Clinician portal & remote monitoring", "FDA / CE regulatory documentation support"],
  },
  {
    id: "clinical-integration",
    title: "Clinical System Integration",
    tagline: "EHR, DICOM, and clinical workflows",
    color: "from-pink-500 to-rose-600",
    deliverables: ["DICOM / BIDS data export", "HL7 FHIR integration for EHR", "Clinical report generation (PDF + structured data)", "Multi-site data federation & anonymization", "IEC 62304 software lifecycle documentation"],
  },
  {
    id: "research-platform",
    title: "Research & Experiment Platform",
    tagline: "Experiment design to publication-ready analysis",
    color: "from-amber-500 to-orange-600",
    deliverables: ["PsychoPy / E-Prime experiment integration", "LSL (Lab Streaming Layer) data synchronization", "MNE-Python / EEGLAB compatible data pipeline", "Statistical analysis & visualization toolkit", "Open-source toolbox contribution & documentation"],
  },
];

/* ─── 10-20 System Visual ─── */
function TenTwentySystem() {
  const [hoveredElectrode, setHoveredElectrode] = useState<string | null>(null);

  const electrodes: { name: string; x: number; y: number; region: string; color: string }[] = [
    // Frontal
    { name: "Fp1", x: 36, y: 12, region: "Prefrontal L", color: "from-blue-400 to-blue-600" },
    { name: "Fp2", x: 64, y: 12, region: "Prefrontal R", color: "from-blue-400 to-blue-600" },
    { name: "F7", x: 18, y: 28, region: "Frontal L", color: "from-cyan-400 to-cyan-600" },
    { name: "F3", x: 36, y: 28, region: "Frontal L", color: "from-cyan-400 to-cyan-600" },
    { name: "Fz", x: 50, y: 25, region: "Frontal mid", color: "from-cyan-400 to-cyan-600" },
    { name: "F4", x: 64, y: 28, region: "Frontal R", color: "from-cyan-400 to-cyan-600" },
    { name: "F8", x: 82, y: 28, region: "Frontal R", color: "from-cyan-400 to-cyan-600" },
    // Central
    { name: "T3", x: 10, y: 50, region: "Temporal L", color: "from-amber-400 to-amber-600" },
    { name: "C3", x: 32, y: 48, region: "Central L", color: "from-green-400 to-green-600" },
    { name: "Cz", x: 50, y: 46, region: "Central mid", color: "from-green-400 to-green-600" },
    { name: "C4", x: 68, y: 48, region: "Central R", color: "from-green-400 to-green-600" },
    { name: "T4", x: 90, y: 50, region: "Temporal R", color: "from-amber-400 to-amber-600" },
    // Parietal
    { name: "T5", x: 20, y: 70, region: "Temporal L", color: "from-amber-400 to-amber-600" },
    { name: "P3", x: 36, y: 68, region: "Parietal L", color: "from-purple-400 to-purple-600" },
    { name: "Pz", x: 50, y: 66, region: "Parietal mid", color: "from-purple-400 to-purple-600" },
    { name: "P4", x: 64, y: 68, region: "Parietal R", color: "from-purple-400 to-purple-600" },
    { name: "T6", x: 80, y: 70, region: "Temporal R", color: "from-amber-400 to-amber-600" },
    // Occipital
    { name: "O1", x: 38, y: 86, region: "Occipital L", color: "from-rose-400 to-rose-600" },
    { name: "Oz", x: 50, y: 88, region: "Occipital mid", color: "from-rose-400 to-rose-600" },
    { name: "O2", x: 62, y: 86, region: "Occipital R", color: "from-rose-400 to-rose-600" },
  ];

  return (
    <div className="relative">
      <p className="text-[10px] text-white/30 uppercase tracking-wider mb-3 font-semibold text-center">
        International 10-20 Electrode System
      </p>
      <div className="relative w-full max-w-xs mx-auto aspect-square">
        {/* Head outline */}
        <svg className="absolute inset-0 w-full h-full" viewBox="0 0 100 100">
          <ellipse cx="50" cy="50" rx="44" ry="46" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="0.5" />
          {/* Nose marker */}
          <path d="M47 4 L50 0 L53 4" fill="none" stroke="rgba(255,255,255,0.15)" strokeWidth="0.5" />
          {/* Ears */}
          <ellipse cx="4" cy="50" rx="3" ry="5" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="0.4" />
          <ellipse cx="96" cy="50" rx="3" ry="5" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="0.4" />
          {/* Midlines */}
          <line x1="50" y1="6" x2="50" y2="94" stroke="rgba(255,255,255,0.05)" strokeWidth="0.3" strokeDasharray="2 2" />
          <line x1="6" y1="50" x2="94" y2="50" stroke="rgba(255,255,255,0.05)" strokeWidth="0.3" strokeDasharray="2 2" />
        </svg>

        {/* Electrodes */}
        {electrodes.map((e) => (
          <motion.div
            key={e.name}
            className="absolute cursor-pointer"
            style={{ left: `${e.x}%`, top: `${e.y}%`, transform: "translate(-50%, -50%)" }}
            onMouseEnter={() => setHoveredElectrode(e.name)}
            onMouseLeave={() => setHoveredElectrode(null)}
            whileHover={{ scale: 1.4 }}
          >
            <div
              className={`w-5 h-5 rounded-full bg-gradient-to-br ${e.color} flex items-center justify-center shadow-sm border border-white/20 ${
                hoveredElectrode === e.name ? "ring-2 ring-accent/50" : ""
              }`}
            >
              <span className="text-[6px] text-white font-bold">{e.name}</span>
            </div>
            {/* Tooltip */}
            {hoveredElectrode === e.name && (
              <motion.div
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className="absolute top-full left-1/2 -translate-x-1/2 mt-1 whitespace-nowrap bg-white/10 backdrop-blur text-white/80 text-[9px] px-2 py-1 rounded-md z-30 border border-white/10"
              >
                <span className="font-bold">{e.name}</span> — {e.region}
              </motion.div>
            )}
          </motion.div>
        ))}
      </div>
      <div className="flex flex-wrap gap-2 justify-center mt-4">
        {[
          { label: "Prefrontal", color: "bg-blue-500" },
          { label: "Frontal", color: "bg-cyan-500" },
          { label: "Central", color: "bg-green-500" },
          { label: "Temporal", color: "bg-amber-500" },
          { label: "Parietal", color: "bg-purple-500" },
          { label: "Occipital", color: "bg-rose-500" },
        ].map((r) => (
          <span key={r.label} className="flex items-center gap-1 text-[9px] text-white/50">
            <span className={`w-2 h-2 rounded-full ${r.color}`} />
            {r.label}
          </span>
        ))}
      </div>
    </div>
  );
}

export default function BrainComputerInterface() {
  const [activeModality, setActiveModality] = useState(0);
  const [activeTab, setActiveTab] = useState<"overview" | "electrodes" | "signals" | "hardware">("overview");
  const [activePipelineStep, setActivePipelineStep] = useState<number | null>(null);
  const [activeServiceIdx, setActiveServiceIdx] = useState<number | null>(null);
  const mod = modalities[activeModality];

  const togglePipeline = useCallback((idx: number) => {
    setActivePipelineStep((prev) => (prev === idx ? null : idx));
  }, []);

  return (
    <section id="bci" className="py-24 bg-primary relative overflow-hidden">
      <div className="absolute top-0 right-0 w-96 h-96 bg-violet-500/5 rounded-full blur-3xl translate-x-1/3 -translate-y-1/3" />
      <div className="absolute bottom-0 left-0 w-80 h-80 bg-blue-500/5 rounded-full blur-3xl -translate-x-1/3 translate-y-1/3" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <span className="inline-block text-accent font-semibold text-sm uppercase tracking-wider mb-3">
            Neurotechnology & Brain-Computer Interfaces
          </span>
          <h2 className="text-3xl md:text-5xl font-bold text-white mb-4">
            Brain-Computer <span className="text-accent">Interface</span>
          </h2>
          <p className="text-white/60 max-w-3xl mx-auto text-lg">
            End-to-end BCI engineering — from EEG/EMG/fNIRS signal acquisition and the 10-20 electrode system
            to real-time neural decoding, neurofeedback platforms, and clinical-grade brain imaging with fMRI & MRI.
          </p>
        </motion.div>

        {/* ── SECTION 1: Signal Modalities ── */}
        <div className="mb-20">
          <h3 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-6 text-center">Signal Modalities</h3>

          {/* Modality tabs */}
          <div className="flex justify-center mb-8">
            <div className="inline-flex bg-white/5 rounded-2xl p-1.5 gap-1 flex-wrap justify-center border border-white/10">
              {modalities.map((m, i) => (
                <button
                  key={m.id}
                  onClick={() => { setActiveModality(i); setActiveTab("overview"); }}
                  className={`px-3 sm:px-4 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all ${
                    i === activeModality
                      ? `bg-gradient-to-r ${m.color} text-white shadow-lg`
                      : "text-white/50 hover:text-white hover:bg-white/10"
                  }`}
                >
                  {m.id.toUpperCase()}
                </button>
              ))}
            </div>
          </div>

          {/* Modality detail */}
          <AnimatePresence mode="wait">
            <motion.div
              key={mod.id}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -15 }}
              transition={{ duration: 0.25 }}
            >
              {/* Header card */}
              <div className={`rounded-2xl border ${mod.borderAccent} ${mod.bgAccent} p-5 mb-6`}>
                <h3 className="text-lg font-bold text-white mb-1">{mod.name}</h3>
                <p className="text-sm text-white/50 mb-3">{mod.tagline}</p>
                <p className="text-xs text-white/40 leading-relaxed">{mod.description}</p>
              </div>

              {/* Sub-tabs */}
              <div className="flex gap-1 mb-6 overflow-x-auto pb-1">
                {(["overview", ...(mod.id === "eeg" ? ["electrodes"] : []), "signals", "hardware"] as const).map((t) => (
                  <button
                    key={t}
                    onClick={() => setActiveTab(t as typeof activeTab)}
                    className={`px-4 py-2 rounded-lg text-xs font-semibold whitespace-nowrap transition-all ${
                      activeTab === t
                        ? "bg-white/10 text-white"
                        : "text-white/40 hover:text-white/60 hover:bg-white/5"
                    }`}
                  >
                    {t === "overview" ? "Specs" : t === "electrodes" ? "10-20 System" : t === "signals" ? "Signal Features" : "Hardware"}
                  </button>
                ))}
              </div>

              {/* Specs tab */}
              {activeTab === "overview" && (
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {Object.entries(mod.specs).map(([key, val], j) => (
                    <motion.div
                      key={key}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: j * 0.05 }}
                      className="bg-white/[0.04] border border-white/10 rounded-xl p-4"
                    >
                      <p className="text-[10px] text-white/30 uppercase tracking-wider mb-1">{key}</p>
                      <p className="text-sm text-white/70 font-medium">{val}</p>
                    </motion.div>
                  ))}
                </div>
              )}

              {/* 10-20 Electrode system (EEG only) */}
              {activeTab === "electrodes" && mod.id === "eeg" && (
                <div className="grid lg:grid-cols-2 gap-8">
                  <TenTwentySystem />
                  <div className="space-y-4">
                    {"electrode_systems" in mod && mod.electrode_systems?.map((sys, j) => (
                      <motion.div
                        key={sys.name}
                        initial={{ opacity: 0, x: 15 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: j * 0.1 }}
                        className="bg-white/[0.04] border border-white/10 rounded-xl p-4"
                      >
                        <h4 className="text-sm font-bold text-white mb-1">{sys.name}</h4>
                        <p className="text-[11px] text-white/40 mb-3">{sys.description}</p>
                        <div className="flex flex-wrap gap-1">
                          {sys.positions.map((p) => (
                            <span key={p} className="text-[9px] font-mono bg-white/10 text-white/60 px-1.5 py-0.5 rounded">
                              {p}
                            </span>
                          ))}
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>
              )}

              {/* Signal features tab */}
              {activeTab === "signals" && (
                <div className="grid sm:grid-cols-2 gap-3">
                  {mod.signal_features.map((sf, j) => (
                    <motion.div
                      key={sf.name}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: j * 0.05 }}
                      className="bg-white/[0.04] border border-white/10 rounded-xl p-4 hover:bg-white/[0.06] transition-colors"
                    >
                      <h4 className="text-sm font-bold text-white mb-1">{sf.name}</h4>
                      <p className="text-[11px] text-white/40 mb-2">{sf.description}</p>
                      <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-accent bg-accent/10 px-2 py-0.5 rounded-full">
                        <svg className="w-2.5 h-2.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                        {sf.application}
                      </span>
                    </motion.div>
                  ))}
                </div>
              )}

              {/* Hardware tab */}
              {activeTab === "hardware" && (
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {mod.hardware.map((hw, j) => (
                    <motion.div
                      key={hw.name}
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: j * 0.04 }}
                      className="bg-white/[0.04] border border-white/10 rounded-xl p-4 hover:bg-white/[0.06] transition-colors"
                    >
                      <div className="flex items-center justify-between mb-2">
                        <h4 className="text-sm font-bold text-white">{hw.name}</h4>
                        <span className={`text-[9px] font-semibold px-2 py-0.5 rounded-full ${mod.bgAccent} ${mod.accent}`}>
                          {hw.channels}
                        </span>
                      </div>
                      <span className="text-[10px] text-white/30 uppercase">{hw.type}</span>
                      <p className="text-[11px] text-white/45 mt-1">{hw.detail}</p>
                    </motion.div>
                  ))}
                </div>
              )}
            </motion.div>
          </AnimatePresence>
        </div>

        {/* ── SECTION 2: BCI Processing Pipeline ── */}
        <div className="mb-20">
          <h3 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-8 text-center">BCI Processing Pipeline</h3>

          {/* Horizontal flow (desktop) */}
          <div className="hidden lg:flex items-start gap-2 mb-6">
            {pipeline.map((step, i) => (
              <div key={step.id} className="flex items-start flex-1">
                <motion.button
                  initial={{ opacity: 0, y: 10 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.08 }}
                  onClick={() => togglePipeline(i)}
                  className={`w-full rounded-xl border p-4 text-center transition-all ${
                    activePipelineStep === i
                      ? "bg-white/[0.08] border-accent/40 shadow-lg shadow-accent/10"
                      : "bg-white/[0.04] border-white/10 hover:bg-white/[0.06]"
                  }`}
                >
                  <span className="text-2xl">{step.icon}</span>
                  <p className="text-xs font-bold text-white mt-2">{step.title}</p>
                </motion.button>
                {i < pipeline.length - 1 && (
                  <svg className="w-6 h-4 text-white/20 flex-shrink-0 mt-8" fill="none" stroke="currentColor" viewBox="0 0 24 16">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2 8h16m0 0l-4-4m4 4l-4 4" />
                  </svg>
                )}
              </div>
            ))}
          </div>

          {/* Mobile: vertical list */}
          <div className="lg:hidden grid grid-cols-2 sm:grid-cols-3 gap-3 mb-6">
            {pipeline.map((step, i) => (
              <button
                key={step.id}
                onClick={() => togglePipeline(i)}
                className={`rounded-xl border p-3 text-center transition-all ${
                  activePipelineStep === i
                    ? "bg-white/[0.08] border-accent/40"
                    : "bg-white/[0.04] border-white/10"
                }`}
              >
                <span className="text-xl">{step.icon}</span>
                <p className="text-[10px] font-bold text-white mt-1">{step.title}</p>
              </button>
            ))}
          </div>

          {/* Pipeline step detail */}
          <AnimatePresence>
            {activePipelineStep !== null && (
              <motion.div
                key={pipeline[activePipelineStep].id}
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <div className={`rounded-2xl border border-accent/30 bg-white/[0.06] p-6`}>
                  <h4 className="font-bold text-white text-lg mb-4 flex items-center gap-2">
                    <span className="text-xl">{pipeline[activePipelineStep].icon}</span>
                    {pipeline[activePipelineStep].title}
                  </h4>
                  <div className="space-y-2">
                    {pipeline[activePipelineStep].steps.map((s, j) => (
                      <motion.div
                        key={j}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: j * 0.06 }}
                        className="flex items-start gap-3"
                      >
                        <div className={`w-6 h-6 rounded-full bg-gradient-to-br ${pipeline[activePipelineStep].color} text-white text-[9px] font-bold flex items-center justify-center flex-shrink-0 mt-0.5`}>
                          {j + 1}
                        </div>
                        <p className="text-sm text-white/60">{s}</p>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* ── SECTION 3: BCI Services ── */}
        <div>
          <h3 className="text-xs font-bold text-white/40 uppercase tracking-widest mb-8 text-center">BCI Engineering Services</h3>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mb-6">
            {bciServices.map((svc, i) => (
              <motion.button
                key={svc.id}
                initial={{ opacity: 0, y: 15 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.06 }}
                onClick={() => setActiveServiceIdx(activeServiceIdx === i ? null : i)}
                className={`group rounded-xl border p-4 text-left transition-all ${
                  activeServiceIdx === i
                    ? "bg-white/[0.08] border-accent/40 shadow-lg shadow-accent/10"
                    : "bg-white/[0.04] border-white/10 hover:bg-white/[0.06]"
                }`}
              >
                <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${svc.color} flex items-center justify-center text-white mb-3 shadow-md`}>
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <h4 className="font-bold text-white text-sm mb-0.5">{svc.title}</h4>
                <p className="text-[10px] text-white/40">{svc.tagline}</p>
              </motion.button>
            ))}
          </div>

          {/* Service detail */}
          <AnimatePresence>
            {activeServiceIdx !== null && (
              <motion.div
                key={bciServices[activeServiceIdx].id}
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
                className="overflow-hidden"
              >
                <div className="rounded-2xl border border-accent/30 bg-white/[0.06] p-6">
                  <h4 className="font-bold text-white text-lg mb-1">{bciServices[activeServiceIdx].title}</h4>
                  <p className="text-xs text-white/40 mb-4">{bciServices[activeServiceIdx].tagline}</p>
                  <h5 className="text-[10px] font-bold text-white/50 uppercase tracking-wider mb-3">Deliverables</h5>
                  <div className="space-y-2">
                    {bciServices[activeServiceIdx].deliverables.map((d, j) => (
                      <motion.div
                        key={j}
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: j * 0.05 }}
                        className="flex items-center gap-2 bg-white/[0.05] border border-white/10 rounded-lg px-4 py-3"
                      >
                        <svg className="w-4 h-4 text-accent flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                        <span className="text-sm text-white/70">{d}</span>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Summary stats */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-3"
        >
          {[
            { value: "6", label: "Signal Modalities" },
            { value: "6", label: "Pipeline Stages" },
            { value: "6", label: "BCI Services" },
            { value: "30+", label: "Hardware Platforms" },
          ].map((stat) => (
            <div
              key={stat.label}
              className="bg-white/[0.05] backdrop-blur-sm rounded-xl border border-white/10 p-3 text-center hover:bg-white/[0.08] transition-colors"
            >
              <p className="text-xl font-bold text-accent">{stat.value}</p>
              <p className="text-[10px] text-white/50 uppercase tracking-wider">{stat.label}</p>
            </div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}
